In this notebook we give a proof of concept of unitary compiling using TFQ.

In [214]:
%load_ext autoreload
%autoreload 2

import sympy 
import numpy as np 
import pandas as pd 
import tensorflow as tf
from utilities.circuit_database import CirqTranslater
from utilities.templates import *
from utilities.variational import Minimizer
from utilities.misc import get_qubits_involved, reindex_symbol, shift_symbols_down
import matplotlib.pyplot as plt 
import tensorflow_quantum as tfq
import cirq
from utilities.compiling import *
from utilities.simplifier import Simplifier

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [226]:
translator = CirqTranslater(3)
circs={}
for block in [1,2]:
    xlayer = x_layer_db(translator, block_id=block)
    zlayer = z_layer_db(translator, block_id=block)
    cnots_layer = cnot_layer(translator, block_id=block)
    if block==1:
        circs[block] = concatenate_dbs([xlayer, zlayer,xlayer, zlayer, zlayer, cnots_layer])
    else:
        circs[block] = concatenate_dbs([xlayer, cnots_layer])

        
circuit_db = concatenate_dbs([c for c in circs.values()])
circuit, circuit_db = translator.give_circuit(circuit_db)

translator.give_circuit(circuit_db,unresolved=False)[0]

                                                           ┌──────┐
(0, 0): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───@────────X─────────Rx(0)───@───────X───
                                                   │        │                 │       │
(0, 1): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───X───@────┼Rx(0)────────────X───@───┼───
                                                       │    │                     │   │
(0, 2): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────X────@─────────Rx(0)───────X───@───
                                                           └──────┘

In [288]:
simplifier = Simplifier(translator)
simplified_db, nsimps = simplifier.reduce_circuit(circuit_db)

In [289]:
translator.give_circuit(simplified_db, unresolved=False)[0]

                                                       ┌──────┐
(0, 0): ───Rz(1.07π)─────Rx(2π)───Rz(0.926π)───@────────X─────────Rx(0)───@───────X───
                                               │        │                 │       │
(0, 1): ───Rz(0)─────────Rx(0)────Rz(0)────────X───@────┼Rx(0)────────────X───@───┼───
                                                   │    │                     │   │
(0, 2): ───Rz(-0.767π)───Rx(2π)───Rz(-1.23π)───────X────@─────────Rx(0)───────X───@───
                                                       └──────┘

In [291]:
shift_need = True
ssdb = simplified_db.copy()
while shift_need is True:
    ss = ssdb["symbol"].dropna()
    prev_s = int(list(ss)[0].replace("th_",""))
    for ind,s in zip(ss.index[1:], ss[1:]):
        current = int(s.replace("th_",""))
        if current - prev_s >1:
            shift_need = True
            from_ind = ind
            ssdb = shift_symbols_down(simplifier.translator, from_ind, ssdb)
            break
        else:
            shift_need = False
    if shift_need is True:

In [292]:
ssdb

    ind symbol  param_value  trainable  block_id
0     6   th_0     3.372523       True         1
1     7   th_1   -12.566411       True         1
2     8   th_1    35.290058       True         1
3     9   th_1    43.982319       True         1
4    10   th_1   -62.831924       True         1
5    11   th_1   -31.415991       True         1
6     6   th_1    -9.655697       True         1
7     7   th_1    12.566413       True         1
8     8   th_1    33.824970       True         1
9     0   None          NaN       True         1
10    3   None          NaN       True         1
11    4   None          NaN       True         1
12    9   th_1     0.000000       True         2
13   10   th_1     0.000000       True         2
14   11   th_1     0.000000       True         2
15    0   None          NaN       True         2
16    3   None          NaN       True         2
17    4   None          NaN       True         2

In [222]:
translator = CirqTranslater(3)
circs={}
for block in [1,2]:
    xlayer = x_layer_db(translator, block_id=block)
    zlayer = z_layer_db(translator, block_id=block)
    cnots_layer = cnot_layer(translator, block_id=block)
    circs[block] = concatenate_dbs([xlayer, zlayer,xlayer, zlayer, zlayer, cnots_layer])

circuit_db = concatenate_dbs([c for c in circs.values()])
circuit, circuit_db = translator.give_circuit(circuit_db)

translator.give_circuit(circuit_db,unresolved=False)[0]

                                                           ┌──────┐
(0, 0): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───@────────X─────────Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───@───────X───
                                                   │        │                                                 │       │
(0, 1): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───X───@────┼Rx(0)────Rz(0)───Rx(0)───Rz(0)───Rz(0)───────────X───@───┼───
                                                       │    │                                                     │   │
(0, 2): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────X────@─────────Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────X───@───
                                                           └──────┘

In [223]:
simplifier = Simplifier(translator)
simplified_db, nsimps = simplifier.reduce_circuit(circuit_db)

In [224]:
translator.give_circuit(simplified_db, unresolved=False)[0]

                                                      ┌──────┐
(0, 0): ───Rz(-0.074π)───Rx(0)───Rz(0.074π)───@────────X─────────Rz(-1.48π)───Rx(0)────Rz(1.48π)───@───────X───
                                              │        │                                           │       │
(0, 1): ───Rz(0.92π)─────Rx(0)───Rz(-0.92π)───X───@────┼Rz(0)────Rx(2π)───────Rz(2π)───────────────X───@───┼───
                                                  │    │                                               │   │
(0, 2): ───Rz(-0.964π)───Rx(0)───Rz(0.964π)───────X────@─────────Rz(-1.55π)───Rx(0)────Rz(1.55π)───────X───@───
                                                      └──────┘

In [225]:
simplified_db

    ind symbol  param_value  trainable  block_id
0     6   th_0    24.901747       True         1
1     7   th_1    15.457678       True         1
2     8   th_2    -3.029189       True         1
3     9   th_3   -25.132719       True         1
4    10   th_4   -12.566378       True         1
5    11   th_5     0.000001       True         1
6     6   th_6     0.230986       True         1
7     7   th_7   -15.457677       True         1
8     8   th_8     3.029195       True         1
9     0   None          NaN       True         1
10    3   None          NaN       True         1
11    4   None          NaN       True         1
12    6  th_15    -4.644344       True         2
13    7  th_16   -12.566411       True         2
14    8  th_17    32.828110       True         2
15    9  th_18   -25.132755       True         2
16   10  th_19    -6.283280       True         2
17   11  th_20   -12.566341       True         2
18    6  th_21   -20.488430       True         2
19    7  th_22    18.849598       True         2
20    8  th_23    17.437317       True         2
21    0   None          NaN       True         2
22    3   None          NaN       True         2
23    4   None          NaN       True         2

In [165]:
translator = CirqTranslater(6)
xlayer = x_layer_db(translator)
zlayer = z_layer_db(translator)

cnots_layer = cnot_layer(translator)
circuit_db = concatenate_dbs([xlayer, zlayer,xlayer, zlayer, zlayer, cnots_layer, cnots_layer])
circuit, circuit_db = translator.give_circuit(circuit_db)

translator.give_circuit(circuit_db,unresolved=False)[0]

(0, 0): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───@───────────────────X───@───────────────────X───
                                                   │                   │   │                   │
(0, 1): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───X───@───────────────┼───X───@───────────────┼───
                                                       │               │       │               │
(0, 2): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────X───@───────────┼───────X───@───────────┼───
                                                           │           │           │           │
(0, 3): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────────X───@───────┼───────────X───@───────┼───
                                                               │       │               │       │
(0, 4): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────────────X───@───┼───────────────X───@───┼───
                                                                   │   │                   │   │
(0, 5): ───Rx(0)───Rz(0)───Rx(0)───Rz(0)───Rz(0)───────────────────X───@───────────────────X───@───

In [155]:
simplifier = Simplifier(translator)

In [156]:
gates_on_qubit, on_qubit_order =  simplifier.get_positional_dbs(circuit, circuit_db)

In [157]:
cnt, simplified_db = simplifier.apply_rule(circuit_db, simplifier.rule_5)
scircuit, simplified_db = translator.give_circuit(simplified_db, unresolved = False)

In [158]:
scircuit

(0, 0): ───Rz(1.02π)─────Rx(0)────Rz(-1.02π)───@───────────────────X───@───────────────────X───
                                               │                   │   │                   │
(0, 1): ───Rz(0.007π)────Rx(2π)───Rz(1.99π)────X───@───────────────┼───X───@───────────────┼───
                                                   │               │       │               │
(0, 2): ───Rz(1.1π)──────Rx(2π)───Rz(0.898π)───────X───@───────────┼───────X───@───────────┼───
                                                       │           │           │           │
(0, 3): ───Rz(0.771π)────Rx(2π)───Rz(1.23π)────────────X───@───────┼───────────X───@───────┼───
                                                           │       │               │       │
(0, 4): ───Rz(-0.997π)───Rx(0)────Rz(0.997π)───────────────X───@───┼───────────────X───@───┼───
                                                               │   │                   │   │
(0, 5): ───Rz(-0.017π)───Rx(2π)───Rz(-1.98π)───────────────────X───@───────────────────X───@───

In [106]:
cnt

2

In [163]:
len(set(simplified_db["block_id"]))

1

In [254]:
translator = CirqTranslater(3)

u1db = u1_layer(translator)
uflip = pd.DataFrame([gate_template(k) for k in [translator.number_of_cnots, 0,0]])
x_layer_db = pd.DataFrame([gate_template(k, param_value=0.) for k in [translator.number_of_cnots + translator.n_qubits+j for j in range(translator.n_qubits)]])
uflip_x = pd.DataFrame([gate_template(k) for k in [translator.number_of_cnots + 1, translator.number_of_cnots+3, 2, 2]])

circuit_db = concatenate_dbs([x_on_all,uflip_x, uflip_x, uflip_x])
circuit, circuit_db  = translator.give_circuit(circuit_db)
gates_on_qubit, on_qubit_order = get_positional_dbs(circuit, circuit_db)
simplified_db = circuit_db.copy()
circuit

(0, 0): ───Rx(th_0)───Rx(th_4)───X───X───Rx(th_6)───X───X───Rx(th_8)───X───X───
                                 │   │              │   │              │   │
(0, 1): ───Rx(th_1)───Rz(th_3)───@───@───Rz(th_5)───@───@───Rz(th_7)───@───@───

(0, 2): ───Rx(th_2)────────────────────────────────────────────────────────────

In [263]:
type_get = lambda x: (x-translator.number_of_cnots)//translator.n_qubits
check_rot = lambda ind_gate: translator.number_of_cnots<= ind_gate <(3*translator.n_qubits + translator.number_of_cnots)

simplification = False
for q, qubit_gates_path in gates_on_qubit.items():
    if simplification is True:
        break
    for order_gate_on_qubit, ind_gate in enumerate(qubit_gates_path[:-1]):
        if simplification is True:
            break
        ind_gate_p1 = qubit_gates_path[order_gate_on_qubit+1]

        if (check_rot(ind_gate) == True) and (check_rot(ind_gate_p1) == False):
            type_0 = type_get(ind_gate)

            control, target = translator.indexed_cnots[str(ind_gate_p1)]
            
            this_qubit = q
            other_qubits = [control, target]
            other_qubits.remove(q)
            other_qubit = other_qubits[0]
            

            if ((type_0 == 0) and (q==control)) or ((type_0== 1) and (q==target)):
                ### free to pass...
                print("0")
                if len(gates_on_qubit[other_qubit]) == 1:
                    simplification = True
                for qord_other, ind_gate_other in enumerate(gates_on_qubit[other_qubit]):
                    if (ind_gate_other == ind_gate_p1): ## check if we find the same cnot on both qubits
                        print("here")
                        cnot_call__q = on_qubit_order[q][order_gate_on_qubit+1]
                        if cnot_call__q == on_qubit_order[other_qubit][qord_other]:## now check if we are applying the gate on both qubits at same time
                            ### it might happen that there's no gate on the other qbit before the cnot, in that case free to comute.
                            if qord_other == 0:
                                simplification = True
                                break
                            else:
                                gate_in_other_qubit_before_cnot = simplified_db.loc[on_qubit_order[other_qubit][qord_other-1]]["ind"]
                                if check_rot(gate_in_other_qubit_before_cnot) == True:
                                    type_gate_other = type_get(gate_in_other_qubit_before_cnot)
                                    print(q, ind_gate, order_gate_on_qubit)
                                    if type_0 != type_gate_other:
                                        simplification = True
                                        print("okkk")
                                        break
                if simplification == True:

                    info_rot = simplified_db.loc[on_qubit_order[q][order_gate_on_qubit]].copy()
                    info_cnot_control = simplified_db.loc[on_qubit_order[q][order_gate_on_qubit+1]].copy()

                    simplified_db.loc[on_qubit_order[q][order_gate_on_qubit]]  = info_cnot_control
                    simplified_db.loc[on_qubit_order[q][order_gate_on_qubit+1]] = info_rot

                    break

0
here
0 9 1
okkk

In [265]:
circuit

(0, 0): ───Rx(th_0)───Rx(th_4)───X───X───Rx(th_6)───X───X───Rx(th_8)───X───X───
                                 │   │              │   │              │   │
(0, 1): ───Rx(th_1)───Rz(th_3)───@───@───Rz(th_5)───@───@───Rz(th_7)───@───@───

(0, 2): ───Rx(th_2)────────────────────────────────────────────────────────────

In [266]:
scircuit, scircuit_db  = translator.give_circuit(simplified_db)

In [130]:
for j in range(10):
    for i in range(10):
        print(i,j)
        
        if i==2:
            break

0 0
1 0
2 0
0 1
1 1
2 1
0 2
1 2
2 2
0 3
1 3
2 3
0 4
1 4
2 4
0 5
1 5
2 5
0 6
1 6
2 6
0 7
1 7
2 7
0 8
1 8
2 8
0 9
1 9
2 9

In [261]:
circuit_db

    ind symbol  param_value  trainable  block_id
0     9   th_0          0.0       True         0
1    10   th_1          0.0       True         0
2    11   th_2          0.0       True         0
3     7   th_3          NaN       True         0
4     9   th_4          NaN       True         0
5     2   None          NaN       True         0
6     2   None          NaN       True         0
7     7   th_5          NaN       True         0
8     9   th_6          NaN       True         0
9     2   None          NaN       True         0
10    2   None          NaN       True         0
11    7   th_7          NaN       True         0
12    9   th_8          NaN       True         0
13    2   None          NaN       True         0
14    2   None          NaN       True         0

In [260]:
simplified_db

    ind symbol  param_value  trainable  block_id
0     9   th_0          0.0       True         0
1    10   th_1          0.0       True         0
2    11   th_2          0.0       True         0
3     7   th_3          NaN       True         0
4     9   th_4          NaN       True         0
5     2   None          NaN       True         0
6     2   None          NaN       True         0
7     7   th_5          NaN       True         0
8     9   th_6          NaN       True         0
9     2   None          NaN       True         0
10    2   None          NaN       True         0
11    7   th_7          NaN       True         0
12    9   th_8          NaN       True         0
13    2   None          NaN       True         0
14    2   None          NaN       True         0

In [268]:
def rule_6(translator, simplified_db, on_qubit_order, gates_on_qubit):
    """
    move cnots to the left, rotations to the right.
    
    IMPORTANT this won't work if the cirucit is too short!
    """
    type_get = lambda x: (x-translator.number_of_cnots)//translator.n_qubits
    check_rot = lambda ind_gate: translator.number_of_cnots<= ind_gate <(3*translator.n_qubits + translator.number_of_cnots)

    simplification = False
    for q, qubit_gates_path in gates_on_qubit.items():
        if simplification is True:
            break
        for order_gate_on_qubit, ind_gate in enumerate(qubit_gates_path[:-1]):
            if simplification is True:
                break
            ind_gate_p1 = qubit_gates_path[order_gate_on_qubit+1]

            if (check_rot(ind_gate) == True) and (check_rot(ind_gate_p1) == False):
                type_0 = type_get(ind_gate)

                control, target = translator.indexed_cnots[str(ind_gate_p1)]

                this_qubit = q
                other_qubits = [control, target]
                other_qubits.remove(q)
                other_qubit = other_qubits[0]


                if ((type_0 == 0) and (q==control)) or ((type_0== 1) and (q==target)):
                    ### free to pass...
                    if len(gates_on_qubit[other_qubit]) == 1:
                        simplification = True
                    for qord_other, ind_gate_other in enumerate(gates_on_qubit[other_qubit]):
                        if (ind_gate_other == ind_gate_p1): ## check if we find the same cnot on both qubits
                            cnot_call__q = on_qubit_order[q][order_gate_on_qubit+1]
                            if cnot_call__q == on_qubit_order[other_qubit][qord_other]:## now check if we are applying the gate on both qubits at same time
                                ### it might happen that there's no gate on the other qbit before the cnot, in that case free to comute.
                                if qord_other == 0:
                                    simplification = True
                                    break
                                else:
                                    gate_in_other_qubit_before_cnot = simplified_db.loc[on_qubit_order[other_qubit][qord_other-1]]["ind"]
                                    if check_rot(gate_in_other_qubit_before_cnot) == True:
                                        type_gate_other = type_get(gate_in_other_qubit_before_cnot)
                                        if type_0 != type_gate_other:
                                            simplification = True
                                            break
            if simplification == True:

                info_rot = simplified_db.loc[on_qubit_order[q][order_gate_on_qubit]].copy()
                info_cnot_control = simplified_db.loc[on_qubit_order[q][order_gate_on_qubit+1]].copy()

                simplified_db.loc[on_qubit_order[q][order_gate_on_qubit]]  = info_cnot_control
                simplified_db.loc[on_qubit_order[q][order_gate_on_qubit+1]] = info_rot 
    return simplification, simplified_db

def apply_rule(original_circuit_db, rule, **kwargs):
    max_cnt = kwargs.get('max_cnt',10)
    simplified, cnt = True, 0
    original_circuit, original_circuit_db = translator.give_circuit(original_circuit_db)
    gates_on_qubit, on_qubit_order = get_positional_dbs(original_circuit, original_circuit_db)
    simplified_db = original_circuit_db.copy()
    while simplified and cnt < max_cnt:
        simplified, simplified_circuit_db = rule(translator, simplified_db, on_qubit_order, gates_on_qubit)
        circuit, simplified_db = translator.give_circuit(simplified_circuit_db)
        gates_on_qubit, on_qubit_order = get_positional_dbs(circuit, simplified_db)
        cnt+=1
    return cnt, simplified_db

In [276]:
translator = CirqTranslater(3)

u1db = u1_layer(translator)
uflip = pd.DataFrame([gate_template(k) for k in [translator.number_of_cnots, 0,0]])
x_layer_db = pd.DataFrame([gate_template(k, param_value=0.) for k in [translator.number_of_cnots + translator.n_qubits+j for j in range(translator.n_qubits)]])
uflip_x = pd.DataFrame([gate_template(k) for k in [translator.number_of_cnots + 1, translator.number_of_cnots+3, 2, 2]])

circuit_db = concatenate_dbs([x_on_all,uflip_x, uflip_x, uflip_x])
circuit, circuit_db  = translator.give_circuit(circuit_db)
gates_on_qubit, on_qubit_order = get_positional_dbs(circuit, circuit_db)
simplified_db = circuit_db.copy()

simplification, ssimplified_db = rule_6(translator, simplified_db, on_qubit_order, gates_on_qubit)

An example that you might enter into a loop! It might be good to apply the rules in some order. Like do the commutation only once, then reduce the circuit..

In [277]:
translator.give_circuit(circuit_db)[0]

(0, 0): ───Rx(th_0)───Rx(th_4)───X───X───Rx(th_6)───X───X───Rx(th_8)───X───X───
                                 │   │              │   │              │   │
(0, 1): ───Rx(th_1)───Rz(th_3)───@───@───Rz(th_5)───@───@───Rz(th_7)───@───@───

(0, 2): ───Rx(th_2)────────────────────────────────────────────────────────────

In [278]:
translator.give_circuit(ssimplified_db)[0]

(0, 0): ───Rx(th_0)──────────────X───Rx(th_4)───X───Rx(th_6)───X───X───Rx(th_8)───X───X───
                                 │              │              │   │              │   │
(0, 1): ───Rx(th_1)───Rz(th_3)───@──────────────@───Rz(th_5)───@───@───Rz(th_7)───@───@───

(0, 2): ───Rx(th_2)───────────────────────────────────────────────────────────────────────

In [279]:
simplification, sssimplified_db = rule_6(translator, ssimplified_db, on_qubit_order, gates_on_qubit)

In [280]:
translator.give_circuit(sssimplified_db)[0]

(0, 0): ───Rx(th_0)───Rx(th_4)───X───X───Rx(th_6)───X───X───Rx(th_8)───X───X───
                                 │   │              │   │              │   │
(0, 1): ───Rx(th_1)───Rz(th_3)───@───@───Rz(th_5)───@───@───Rz(th_7)───@───@───

(0, 2): ───Rx(th_2)────────────────────────────────────────────────────────────